// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iueguqkzpkbncwhglamc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZWd1cWt6cGtibmN3aGdsYW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODgxMDUsImV4cCI6MjA2NTQ2NDEwNX0.fJwPcoL9dYRmrlKWfEV9YVFE5HeHgmFRwyQhg4TFzcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);